version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: v2
  ignore:
  - dependency-name: rector/rector
    versions:
    - 0.9.0
